### ISSUE TITLE
Magento 1 setup

### ISSUE THREAD

**Issue by chek** [markoshust/docker-magento#101]
Trying to setup magento 1.
Doing all the same as magento 2 just replace compose/magento-2 with compose/magento-1, downloading 1.8.0.0 version.
There is no bin/setup script, i copied it and bin/magento from magento-2.

When i run bin/setup, i got:
_chmod: cannot access 'bin/magento': No such file or directory
Could not open input file: ./bin/magento
Correcting filesystem permissions...
Filesystem permissions corrected.
Turning on developer mode..
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bin/magento\": stat bin/magento: no such file or directory": unknown
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bin/magento\": stat bin/magento: no such file or directory": unknown_

I can access to install wizard, but when saving on configuration tab i got:
_The URL "http://magento2.test/" is not accessible.
Error parsing body - doesn't seem to be a chunked message_

Also it mentioned i should setup Composer Authentication in ./src/auth.json
but this file also not exists.

I missing something? Can someone help me and explain what i doing wrong?

**Comment by markoshust** [comment]
Since m1 is an old version, I'm not going to take the time to build a bin/setup for it. However, I would totally take a PR for it!
