### ISSUE TITLE
bin/start The system cannot find the path specified.

### ISSUE THREAD

**Issue by itsazzad** [markoshust/docker-magento#105]
`bin/start` command outputting `The system cannot find the path specified.`

`$ bin/start`
```
Creating markoshust-docker-magento_db_1 ... done
Creating markoshust-docker-magento_phpfpm_1 ... done
Creating markoshust-docker-magento_app_1    ... done
Initiating bi-directional sync between host & containers...
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
All containers have started successfully.
```

![image](https://user-images.githubusercontent.com/54909/47803161-10991e00-dd5c-11e8-900c-8027cc3cd17d.png)

**Comment by ryanjavens** [comment]
I'm encountering a similar issue. Which magento container are you using (i.e. magento-2, magento-2-windows, magento-1)?

**Comment by markoshust** [comment]
yes, please let us know what operating system, m1 or m2, windows or mac, etc.

**Comment by itsazzad** [comment]
@markoshust Windows 10 Pro

**Comment by markoshust** [comment]
Closing this in favor of https://github.com/markoshust/docker-magento/issues/100 -- the Windows docker compose setup needs some work
