### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bin/magento\": stat bin/magento: no such file or directory": unknown

### ISSUE THREAD

**Issue by magefan** [markoshust/docker-magento#107]
When we run the setup command
`bin/setup mymagento.test`

get this error
```

chmod: cannot access 'bin/magento': No such file or directory
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bin/magento\": stat bin/magento: no such file or directory": unknown
Correcting filesystem permissions...
find: 'pub/static': No such file or directory
find: 'pub/media': No such file or directory
find: 'app/etc': No such file or directory
find: 'pub/static': No such file or directory
find: 'pub/media': No such file or directory
find: 'app/etc': No such file or directory
chmod: cannot access 'bin/magento': No such file or directory
Filesystem permissions corrected.
Turning on developer mode..
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bin/magento\": stat bin/magento: no such file or directory": unknown
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bin/magento\": stat bin/magento: no such file or directory": unknown
root@dev-lt:/home/dev/docker4/magento-2# 
```
do you have any ideas?
Tnx.

**Comment by markoshust** [comment]
what operating system are you on?

**Comment by magefan** [comment]
@markoshust , thank you for the response. We are on Ubuntu 16.04, using "magento-2" folder

**Comment by wsbrs** [comment]
@markoshust , the same issue:
* Ubuntu 18.04
* Docker version 17.12.1-ce, build 7390fc6

**Additional information.**
All directories in the container which are mounted to the `appdata` volume contain file `docker.sock`  instead of actual content.
Here's an output from the terminal:
```
app@c9fea5aae32c:~/html$ pwd
/var/www/html
app@c9fea5aae32c:~/html$ ls
CHANGELOG.md	     auth.json.sample  grunt-config.json.sample  phpserver
COPYING.txt	     bin	       index.php		 pub
Gruntfile.js.sample  composer.json     lib			 setup
LICENSE.txt	     composer.lock     nginx.conf.sample	 update
LICENSE_AFL.txt      dev	       package.json.sample	 var
app		     generated	       php.ini.sample		 vendor
app@c9fea5aae32c:~/html$ 
app@c9fea5aae32c:~/html$ ls app
docker.sock
app@c9fea5aae32c:~/html$ ls bin
docker.sock
app@c9fea5aae32c:~/html$ ls lib
docker.sock
app@c9fea5aae32c:~/html$ ls vendor
docker.sock
app@c9fea5aae32c:~/html$ ls generated/
docker.sock
```

**Comment by didesignbg** [comment]
Hi, it's the same for me. Upon inspecting your code
`magento-2/docker-compose.yml`
```
      - appdata:/sock
      - appdata:/var/www/html/app
      - appdata:/var/www/html/bin
      - appdata:/var/www/html/dev
      - appdata:/var/www/html/generated
      - appdata:/var/www/html/lib
      - appdata:/var/www/html/phpserver
      - appdata:/var/www/html/pub
      - appdata:/var/www/html/setup
      - appdata:/var/www/html/update
      - appdata:/var/www/html/var
      - appdata:/var/www/html/vendor
```
What happens apdata volume is created and it's conected with unix socket. So every folder (like /var/www/html/bin) contains a socket file expected behaviour. 
I see that you copy all directories after that using
`docker cp $(docker-compose ps|grep phpfpm|awk '{print $1}'):/var/www/html/$1 src/`
probably on Mac due to the delegated volume implementation, this works, but as expected on linux it has no power.
Thus for linux user I would propose just to comment all appdata volumes after the socket is attached, and comment the bin/copydirall call in `bin/start`.
@markoshust maybe it's a good idea to create `magento2-mac` folder as native docker doesn't need those optimizations.

**Comment by markoshust** [comment]
@didesignbg  confirmed,  yes uncomment everything below appdata:/sock and it should all work for linux. i'm adding a note in the docker compose file and the build should be out shortly.

**Comment by aleromano89** [comment]
I am on mac (os x el capitan), and I have the same issue.
I followed the steps related to "Setup a New Magento 2 Project", by downloading the source code of magento 2.3 by bin/download ...

How can I solve?
thanks

**Comment by asma-postpay** [comment]
Hi Mark @markshust 
i was working on your docker image using Macbook pro , the CPU was : Quad-Core Intel Core i5 , and it was working perfectly
after moving to Apple M1 Pro Chip  , i'm getting the same issue above , 
i copied the same src folder and the same db , 

Please let me know your thoughts about that 
Thanks

**Comment by aveshnaik007** [comment]
I got the same issue. I ran 

Fix Ownership: bin/fixowns
Fix Permissions: bin/fixperms
Restart Containers: bin/restart

This fixed the issue
