### ISSUE TITLE
Xdebug not working on linux

### ISSUE THREAD

**Issue by lumnn** [markoshust/docker-magento#108]
PHP ini config recently changed the `xdebug.remote_host` to `host.docker.internal` which doesn't work properly on linux, please have a look on this issue: https://github.com/docker/for-linux/issues/264

**Comment by markoshust** [comment]
This is an issue with Docker on non-mac machines, however a workaround I'm adding to the readme is:

```
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment below two lines & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    #extra_hosts:
    #  - "host.docker.internal:IP"
```

This will be pushed out EOD today
