### ISSUE TITLE
Improve performance of Setup:di:compile

### ISSUE THREAD

**Issue by sy-salvo** [markoshust/docker-magento#109]
Hi Mark, 
thanks for your great job, we're using it in many projects and is very smoothly. 
I'm facing some difficulty on setup:di:compile veery slow in a Macbook pro late 2012 docker installation.
The macbook has been upgraded with ssd, 16gb ram and also browsing magento2 website is ok. 
setup:di:compile is taking a very long time (both on simple and bigger projects)
thansk for support ;)

**Comment by corbinu** [comment]
@sy-salvo Do you know is your drive HFS+ or APFS formatted?

**Comment by sy-salvo** [comment]
@corbinu APFS

**Comment by corbinu** [comment]
Shoot ok that won't help then. Unfortunately Docker for Mac does slow to a crawl when a large number of files are changed in a volume shared with the host.

**Comment by markoshust** [comment]
how slow is too slow?

do you have docker allocating RAM properly with Docker for Mac > Preferences > Advanced > Memory? should have at least 4GB allocated there for proper usage.

i'm going to close until we have more info on this, as this doesn't appear to be an issue afaik. the setup di compile does take a long time.
