### ISSUE TITLE
502 connect to docker.sock failed: Socket not working on Ubuntu for php-fpm

### ISSUE THREAD

**Issue by uabassguy** [markoshust/docker-magento#115]
2019/01/01 01:29:40 [crit] 9#9: *3 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "magento2.test"
172.20.0.1 - - [01/Jan/2019:01:29:40 +0000] "GET / HTTP/1.1" 502 576 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "-"

**Comment by uabassguy** [comment]
deleted the containers and used the setup script again seems to have fixed the socket issue.

**Comment by marvinosswald** [comment]
I have the same issue, on a manual installation with existing source code, how could i debug this ?
