### ISSUE TITLE
Use composer cache

### ISSUE THREAD

**Issue by AurelienLavorel** [markoshust/docker-magento#117]
On **bin/setup** step, you should copy host composer cache and host composer auth to avoid download of sources.

I can make the PR, if it's fine for you.

**Comment by markoshust** [comment]
the entire `~/.composer` dir is host-bind mounted, so things will even cache across projects https://github.com/markoshust/docker-magento/blob/master/compose/magento-2/docker-compose.dev.yml#L10

i changed composer auth.json a while ago so each project can have it's own creds. just copy auth.json into the root of your install and do a `bin/copytocontainer auth.json`. i used to host-bind mount this file, but this method offers more flexibility when working with many projects locally.

**Comment by michael-pure** [comment]
@markshust _Thanks for the awesome repo and great work!_

On my host machine the Composer cache exists at `~/.cache/composer` and there's also a `~/.composer` directory which only has `auth.json` and a couple connection key files.

When the container is created, it downloads everything fresh. (no cache hits) I'm looking at symlinking `~/.composer/cache` or changing my local `$COMPOSER_CACHE_DIR` to correct the location.

Thought I'd give you a heads up though as I'm running repeated tests and seeing package downloads every time. If you have another recommendation, I'd be glad to have it though.
