### ISSUE TITLE
Error volume with composer.json

### ISSUE THREAD

**Issue by gabs77** [markoshust/docker-magento#119]
After uploaded your git repository, I don't download a repository magento but i push a composer.json and composer.lock in the src directory.
Next, I execute bin/setup

I met 2 problems : 
- In the container, the composer files are not files but directory
- Error response from daemon: Error processing tar file(exit status 1): cannot overwrite directory "/composer.json" with non-directory "/"

**Comment by markoshust** [comment]
you can't clone out this repo and run from there, it won't work. follow the setup readme at https://github.com/markoshust/docker-magento#quick-setup

**Comment by gabs77** [comment]
Step to reproduce :

1 . `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.1`
2. `bin/start`
3. `bin/cli ls -l` 
Result : 
-rw-r--r--  1 root root   2298 Apr 26 03:19 composer.json

4. `git add src/composer.json`
5. `git commit -m 'test'`
6. `git checkout -b feature/test`
7. `echo -n '1' > src/composer.json`
8. `git add src/composer.json`
9. `git commit -m 'test'`
10. `bin/cli ls -l` 
Result : 
-rw-r--r--  1 root root   1 Apr 26 03:19 composer.json

11. `git checkout master` 
12. `bin/cli ls -l` 
Result : 
-?????????  ? ?    ?         ?            ? composer.json

When we mount a file and not a folder and this file has changes durant a branch changes, we need to restart the docker-compose
