### ISSUE TITLE
Feature request: Setup scripts for Windows

### ISSUE THREAD

**Issue by rhino-corey** [markoshust/docker-magento#82]
I have been trying to get the setup scripts in the ./bin directory to run properly on Windows 10 for a while and have made little progress. I've tried under WSL, Cygwin, and Babun, but it's just a struggle. The biggest problem is running the CLI commands. You'll get $'\r': command not found and the input device is not a TTY.

It would be great if there was an alternate set of scripts that would run easily on Windows, like Powershell.

**Comment by markoshust** [comment]
thanks for the report, i don't have a windows machine so i can't test. if someone can make a pr, i can make a new `compose/magento-2-windows` folder up there as a sample setup on windows with those custom cli commands. definitely open to taking in a PR for this :)

**Comment by rhino-corey** [comment]
I have a PR coming soon. Just doing some final testing on the scripts.

**Comment by zsoerenm** [comment]
I needed Windows support as well. Here is the corrosponding pull request: https://github.com/markoshust/docker-magento/pull/83
