### ISSUE TITLE
Change nginx conf for magento 2

### ISSUE THREAD

**Issue by gjportegies** [markoshust/docker-magento#84]
I've setup the docker for magento 2 on MacOS and everything worked perfectly.
Than I've changed the code in the src directory with a fullpackage template theme (just another magento project).

I need to run the /setup but I'm getting 403 forbidden messages.

<img width="1051" alt="schermafbeelding 2018-03-09 om 23 35 34" src="https://user-images.githubusercontent.com/6707410/37233314-00ceb1a6-23f3-11e8-843a-f1cf2128eda0.png">

How can I change the config of nginx so I am able to run the setup?

**Comment by markoshust** [comment]
You can see how to override the nginx.conf file by looking at the composer setup for magento 1 https://github.com/markoshust/docker-magento/tree/master/compose/magento-1
