### ISSUE TITLE
./bin directory scripts wont run on windows

### ISSUE THREAD

**Issue by Almusamim** [markoshust/docker-magento#87]
I'm getting this error when i try to run any setup command
```
$ ./bin/download 2.2.2
bash: ./bin/download: No such file or directory
```

**Comment by Almusamim** [comment]
Sorry I missed this part

``PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned``

**Comment by markoshust** [comment]
Ok, guess you figured it out
