### ISSUE TITLE
Error when launching initloopback

### ISSUE THREAD

**Issue by VincentMarmiesse** [markoshust/docker-magento#88]
Hello,

Thanks for your work, I'm having the following issue when I lauch the command `./bin/initloopback`:

```
alias: Unknown host
ifconfig: `--help' gives usage information.
bash: /Library/LaunchDaemons/com.network.alias.plist: No such file or directory
chmod: can't access to '/Library/LaunchDaemons/com.network.alias.plist': No such file or directory
chown: can't access to '/Library/LaunchDaemons/com.network.alias.plist': No such file or directory
sudo: launchctl : command not found
```

Any idea?

I'm using Fedora 28.

Thanks!

**Comment by VincentMarmiesse** [comment]
Hi,

No I'm using Fedora 28. This error looks like a macOS error with `/Library/XXX`.

Should I do something else on Linux?

**Comment by markoshust** [comment]
Ah, yes this hasn't been tested on Fedora, however it should be simple. 

The main thing we do on linux/mac is:
`sudo ifconfig lo0 alias 10.254.254.254 255.255.255.0`

Then, just make sure this alias is also applied at startup.

It appears info on setting up aliases in Fedora is at http://www.unixwerk.eu/linux/redhat/ipalias.html -- I would also perhaps ask the question on stackoverflow to see what the equivalent of the `bin/initloopback` script is in Fedora.

**Comment by VincentMarmiesse** [comment]
Thanks for your answer, here is the command I ran: 
```
sudo ip addr add 10.254.254.254 dev lo label lo:0
```

**Comment by VincentMarmiesse** [comment]
No indeed!

Here are the command to make sure it will persist (taken from the doc you linked):

```
vi /etc/sysconfig/network-scripts/ifcfg-lo:0
ISALIAS=yes
DEVICE=lo:0
ONBOOT=yes
BOOTPROTO=none
IPADDR=10.254.254.254
NETMASK=255.255.255.0
TYPE=Ethernet
```

and then 
```
ln /etc/sysconfig/network-scripts/ifcfg-lo:0 /etc/sysconfig/networking/devices/ifcfg-lo:0
ln /etc/sysconfig/network-scripts/ifcfg-lo:0 /etc/sysconfig/networking/profiles/default/ifcfg-lo:0
```
