### ISSUE TITLE
There should be an easy way to create SSH keys for private repository access

### ISSUE THREAD

**Issue by pocketprogrammer** [markoshust/docker-magento#89]
For existing Magento 2 projects, we load many of our modules via composer from private bitbucket repositories. We use SSH authentication for these repositories, and the docker container running composer must be authenticated to pull down the repositories.

Now I realize if I run composer locally it will sync the vendor directory and all is well, but I am not always on a machine which has all of the platform requirements installed, which can cause issues.

I was able to get this working after messing around for a while, but basically I had to generate ssh keys in the phpfpm container, change ownership of the /var/www directory to app user, and store the keys in /var/www/.ssh because that is where composer attempts to find them and where it stores the bitbucket.org host in the known_hosts file.

Once all of the permissions and ssh keys were in place it ran nicely, but I feel this should be in the configuration of the docker containers. Preferably there would be an option to generate new SSH keys by default, or specify local SSH keys to be synced from the host to the container.

My experience with all of the above is fairly limited, so any other suggestions are welcome, this is just how I solved an issue when working with an existing project.

Cheers!

**Comment by markoshust** [comment]
Seems specific to your use-case, but should be able to do this with volume mounting ssh keys. Nothing we can do here to aid with this, sorry.

**Comment by vaseemishak** [comment]
you can sync your host private key to container .
under
```
services:
  app:
    volumes: &appvolumes
```
 put thhe line below.
`- ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:delegated`

@markshust it will be nice a nice feature.

**Comment by markshust** [comment]
This isn't a common ask, and seems like you already have what you need. I don't think there is anything we need to do here? 🤷‍♂️

**Comment by vaseemishak** [comment]
yes your are right  ,But  I face this issue all time on docker because am working with privates repo sometimes. 
May be a comment line in dev.yml will help  ?.

By the way your docker is best for magento 2 dev . Thanks for your good work. ✌🏻

**Comment by markshust** [comment]
@vaseemishak sure thing, since this has been requested a few times I think that will work :) adding the comment to the next release

**Comment by cengizcoskun** [comment]
I just had this problem and found this solution. Really so good idea Vaseem!

Thank you so much! 👍

**Comment by GamesmenJordan** [comment]
Also experienced this as an issue. We use a number of git repositories for modules and it is not exactly an uncommon occurrence. I think it might be worth documenting this workaround at the very least.
