### ISSUE TITLE
Autoload error trying to get Magento 2.2.2 EE Working

### ISSUE THREAD

**Issue by kreativedev** [markoshust/docker-magento#90]
I have all the docker containers running, but no matter what I do I get:
```
Autoload error
We can't read some files that are required to run the Magento application. This usually means file permissions are set incorrectly.
```
I've tried running the fixperms script but just get this output:
```
./bin/fixperms 
Correcting filesystem permissions...
chmod: changing permissions of 'var/composer_home/keys.tags.pub': Operation not permitted
chmod: changing permissions of 'var/composer_home/keys.dev.pub': Operation not permitted
find: `vendor': No such file or directory
chmod: changing permissions of 'var/composer_home': Operation not permitted
find: `vendor': No such file or directory
Filesystem permissions corrected.
```
This is on an Ubuntu 18.04 install if that makes any difference. Any insight into what may be wrong?

**Comment by markoshust** [comment]
Is this still happening for you? I haven't tested this setup on Ubuntu yet but it should work just fine.

**Comment by sajidunnar** [comment]
Having  same error on ubuntu 18.04  with community edition 2.2.4

app@cfcba2db48eb:~/html/var$ ls -ltrha
total 36K
-rw-r--r--  1 app  app   126 May  1 20:21 .htaccess
drwxr-xr-x  2 root root 4.0K Jun 16 03:28 composer_home
drwxr-xr-x 14 app  app  4.0K Jun 16 22:36 ..

**Comment by markoshust** [comment]
Looks like composer_home directory is owned by root. This should be owned
by app user.

**Comment by kreativedev** [comment]
This is still happening and I'm still unable to get an existing Magento 2.2.2 EE site working.

I've tried changing ownership of var/composer_home

`$ chown -R app:app composer_home/
chown: changing ownership of 'composer_home/keys.tags.pub': Operation not permitted
chown: changing ownership of 'composer_home/keys.dev.pub': Operation not permitted
chown: changing ownership of 'composer_home/': Operation not permitted
`
Any ideas?

**Comment by cctorres** [comment]
> This is still happening and I'm still unable to get an existing Magento 2.2.2 EE site working.
> 
> I've tried changing ownership of var/composer_home
> 
> `$ chown -R app:app composer_home/ chown: changing ownership of 'composer_home/keys.tags.pub': Operation not permitted chown: changing ownership of 'composer_home/keys.dev.pub': Operation not permitted chown: changing ownership of 'composer_home/': Operation not permitted ` Any ideas?

Sorry for ask many years later, but did you resolve this? I am having the same error after run

bin/setup-domain xxxxx xxxxx
