### ISSUE TITLE
HTTP request took too long to complete - magento-1

### ISSUE THREAD

**Issue by amarroni** [markoshust/docker-magento#91]
Hi Mark as I told you via Slack, I'm trying to setup a M1 environment/

[behavior]
running ./bin/start receiving ERROR:
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

[Expected]
download imges and create containers.

**Comment by markoshust** [comment]
Are you on Windows or Mac? I haven't ever experienced this issue. It almost sounds like your Docker for Mac instance needs to be restarted or isn't properly setup. There's no reason Docker Compose should be timing out here. Please try to re-setup and re-build from latest docker-compose.yml file and reopen this ticket if you are still having issues.
