### ISSUE TITLE
Symfony Issue

### ISSUE THREAD

**Issue by RichDKick** [markoshust/docker-magento#94]
Hi 

I am getting the below error when setting up a new project on Mac after running the ./bin/setup command

Correcting filesystem permissions...
Filesystem permissions corrected.
Turning on developer mode..

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "deploy:mode" namespace.

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "indexer" namespace.

In my browser i'm getting the below error

1 exception(s):
Exception #0 (Exception): Unable to proceed: the maintenance mode is enabled. 

Exception #0 (Exception): Unable to proceed: the maintenance mode is enabled. 
#0 /var/www/html/vendor/magento/framework/App/Bootstrap.php(254): Magento\Framework\App\Bootstrap->assertMaintenance()
#1 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#2 {main}

Any help would be great thanks.

**Comment by RichDKick** [comment]
Just a note i managed to get it to work when changing the version of magento

from: ./bin/download 2.2.4
to: ./bin/download 2.2.2

**Comment by markoshust** [comment]
Closing as non-issue, but this is not specific to version of Magento. Most likely the volume mount wasn't looking at the correct location or Magento was not yet downloaded before `bin/setup` was ran.
