### ISSUE TITLE
How can I install nodejs and npm

### ISSUE THREAD

**Issue by sanutryzens** [markoshust/docker-magento#96]
Can you please help me to install nodejs and npm on container?
Sudo won't help as it throwing no such command and without sudo permission denied

Thanks

**Comment by haelbichalex** [comment]
I also need npm to install and use grunt for .less compiling

**Comment by markoshust** [comment]
im working on this

**Comment by markoshust** [comment]
this is now included in php-4 tags

**Comment by adrianalin89** [comment]
how can I change the version installed to an older one :D sorry 
i see the added script here

RUN apt-get install -y gnupg \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
  && apt-get install -y nodejs \
  && mkdir /var/www/.config /var/www/.npm \
  && chown app:app /var/www/.config /var/www/.npm \
  && npm install -g grunt-cli

but is it possible just like in the tutorial  'Install a new PHP extension by building a custom Docker image' to change  the installed version of node

What would even go between the user switching... will need to remove node and reinstall it?

**Comment by rangerz** [comment]
@adrianalin89 
Your custom `Dockerfile` directly use markshust's [Dockerfile](https://github.com/markshust/docker-magento/blob/master/images/php/8.1/Dockerfile) - make sure copy the `conf` folder
