### ISSUE TITLE
How to increase memory limit?

### ISSUE THREAD

**Issue by adamkingfisher** [markoshust/docker-magento#97]
Hi,

Installed on Windows 10 using Docker Toolbox for Windows, all is working perfectly apart from I cannot increase the memory assigned to the containers. I've changed the docker-compose to version 2 and added mem_limit to the compose file but all my efforts are ignored and replaced with a default value of  995.6MiB.

Any help would be much appreciated.

Thanks,
Adam

**Comment by anatolij-p** [comment]
On mac you have an option in Docker configuration, not sure how do you do it in win.

You can check it with very useful tool DockStation (available for most platforms).

![screen shot 2018-06-18 at 22 17 58](https://user-images.githubusercontent.com/17332039/41559802-7b455006-7345-11e8-871a-12cb1dfce1f7.jpg)
![screen shot 2018-06-18 at 22 18 29](https://user-images.githubusercontent.com/17332039/41559826-8fa0e312-7345-11e8-8bb4-cd3960ca1cb2.jpg)

**Comment by adamkingfisher** [comment]
Thanks for the assistance anatolij-p. Docker for Windows (Only on Windows Pro) has a similar solution. For the Legacy Docker Toolbox for Windows solution I have had to remove the default docker machine and create a new one, passing through parameters.

e.g.
docker-machine create -d virtualbox --virtualbox-cpu-count=-1 --virtualbox-memory=4000 --virtualbox-disk-size=15000 default

**Comment by anatolij-p** [comment]
No problem anytime.
