### ISSUE TITLE
Why is initloopback needed?

### ISSUE THREAD

**Issue by jalogut** [markoshust/docker-magento#99]
This is not an issue, just a curious question about `initloopback`

* Why is `./bin/initloopback` exactly needed? 
* Wouldn't work without that is using the ip `127.0.0.1` on the `/etc/hosts`?
* Is it maybe only required for xdebug? 

Thanks in advance for taking the time to clarify that.

**Comment by markoshust** [comment]
this is a very good question, one i cannot answer 100%. i do know that there were issues with docker + debug, and this solved the issue.

that said, i believe using `docker.for.mac.localhost` was a possible solution, but i didn't like how it was mac-specific. this build is meant to be used on mac, windows and linux. this hostname was updated to `host.docker.internal` in 18.03, however i'm not 100% sure that works within linux. so regardless, 10.254.254.254 was a platform-agnostic solution that seems to solve any issues with this.
